version: '3.8'

services:
  # PostgreSQL Database for Development
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: fadl_dashboard_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - dev-network

  # Redis for Development
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - dev-network

  # Development Database Initialization
  db-init:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=fadl_dashboard_dev
      - DB_USER=postgres
      - DB_PASSWORD=dev_password_123
    command: sh -c "npm install && npm run db:init"
    depends_on:
      - db
    networks:
      - dev-network

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  dev-network:
    driver: bridge
